[profile.default]
solc = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
extra_output = ["storageLayout"]

[fmt]
line_length = 180
tab_width = 4
bracket_spacing = true
int_types = 'long'
quote_style = 'double'
number_underscore = 'thousands'
multiline_func_header = 'params_first'

[fuzz]
runs = 1024